version: "3.9"

services:

  courseorganiser_mongo_mongo_1:
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: db2
    volumes:
      - ./mongo/init.js:/docker-entrypoint-initdb.d/init.js
    ports:
      - 27018:27017

#networks:
#  multiple-db: